name: Deploy Frontend

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        build-args: |
          VITE_API_URL=${{ secrets.VITE_API_URL }}
          VITE_API_KEY=${{ secrets.VITE_API_KEY }}
          VITE_STRIPE_TEST_KEY=${{ secrets.VITE_STRIPE_TEST_KEY }}
    
    - name: Deploy to VPS 1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST_1 }}
        username: ${{ secrets.VPS_USERNAME_1 }}
        key: ${{ secrets.VPS_SSH_KEY_1 }}
        script: |
          cd ~/fitboks
          docker compose pull frontend
          docker compose down frontend
          docker compose up -d frontend --force-recreate
          docker compose logs frontend