name: Deploy Frontend

on:
  push:
    branches: [ "156-setup-deploy-script" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    strategy:
      matrix:
        vps: [1, 2, 3]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:vps${{ matrix.vps }}
        build-args: |
          VITE_API_URL=${{ secrets[format('VITE_API_URL_{0}', matrix.vps)] }}
          VITE_API_KEY=${{ secrets.VITE_API_KEY }}
          VITE_STRIPE_TEST_KEY=${{ secrets.VITE_STRIPE_TEST_KEY }}
    
    - name: Update docker-compose and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets[format('VPS_HOST_{0}', matrix.vps)] }}
        username: ${{ secrets[format('VPS_USERNAME_{0}', matrix.vps)] }}
        key: ${{ secrets[format('VPS_SSH_KEY_{0}', matrix.vps)] }}
        script: |
          # Update the frontend service in docker-compose to use the specific tag
          sed -i 's|image: fitboks/frontend:latest|image: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:vps${{ matrix.vps }}|g' docker-compose.yml
          
          # Pull the new image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:vps${{ matrix.vps }}
          
          # Restart the frontend service
          docker-compose up -d frontend